recipe: default.v1

language: en

# alternative pipeline
pipeline:
- name: SpacyNLP
  model: "en_core_web_md"
  case_sensitive: false
- name: SpacyTokenizer
- name: RegexFeaturizer
  case_sensitive: false
- name: SpacyFeaturizer
- name: DIETClassifier
  epochs: 1
  constrain_similarities: true
- name: "DucklingEntityExtractor"
  url: "http://localhost:8000"
  dimensions: ["time", "number"]
  locale: "en_EN"
  timezone: "Europe/Berlin"
  timeout: 3
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 2
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3

policies:
- name: TEDPolicy
  max_history: 10
  epochs: 5
  constrain_similarities: true
- name: AugmentedMemoizationPolicy
  max_history: 4
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_listen"
  enable_fallback_prediction: true
assistant_id: 20240121-114352-external-ranch
