recipe: default.v1

language: en

# main pipeline
pipeline:
- name: WhitespaceTokenizer
  case_sensitive: False
- name: RegexFeaturizer
  case_sensitive: False
- name: CountVectorsFeaturizer
  lowercase: True
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 1
  constrain_similarities: True
  entity_recognition: False
- name: CRFEntityExtractor
  "features": [
    ["low", "title", "upper"],
    [
      "bias",
      "low",
      "prefix5",
      "prefix2",
      "suffix5",
      "suffix3",
      "suffix2",
      "upper",
      "title",
      "digit",
      "pattern",
      "text_dense_features"
    ],
    ["low", "title", "upper"],
  ]
  "max_iterations": 50
  "L1_c": 0.1
  "L2_c": 0.1
- name: "DucklingEntityExtractor"
  url: "http://localhost:8000"
  dimensions: ["time", "number"]
  locale: "en_EN"
  timezone: "Europe/Berlin"
  timeout : 3
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 2
  constrain_similarities: True
- name: FallbackClassifier
  threshold: 0.5

policies:
- name: TEDPolicy
  max_history: 10
  epochs: 5
  constrain_similarities: True
- name: AugmentedMemoizationPolicy
  max_history: 4
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_listen"
  enable_fallback_prediction: True
# alternative pipeline
# pipeline:
# - name: WhitespaceTokenizer
#   case_sensitive: False
# - name: RegexFeaturizer
#   case_sensitive: False
# - name: CountVectorsFeaturizer
#   lowercase: True
#   analyzer: "char_wb"
#   min_ngram: 1
#   max_ngram: 4
# - name: DIETClassifier
#   epochs: 1
#   constrain_similarities: True
#   entity_recognition: False
# - name: CRFEntityExtractor
#   "features": [
#     ["low", "title", "upper"],
#     [
#       "bias",
#       "low",
#       "prefix5",
#       "prefix2",
#       "suffix5",
#       "suffix3",
#       "suffix2",
#       "upper",
#       "title",
#       "digit",
#       "pattern",
#       "text_dense_features"
#     ],
#     ["low", "title", "upper"],
#   ]
#   "max_iterations": 50
#   "L1_c": 0.1
#   "L2_c": 0.1
# - name: "DucklingEntityExtractor"
#   url: "http://localhost:8000"
#   dimensions: ["time", "number"]
#   locale: "en_EN"
#   timezone: "Europe/Berlin"
#   timeout : 3
# - name: EntitySynonymMapper
# - name: ResponseSelector
#   epochs: 2
#   constrain_similarities: True
# - name: FallbackClassifier
#   threshold: 0.5

# policies:
# - name: TEDPolicy
#   max_history: 10
#   epochs: 5
#   constrain_similarities: True
# - name: AugmentedMemoizationPolicy
#   max_history: 4
# - name: MemoizationPolicy
# - name: RulePolicy
#   core_fallback_threshold: 0.4
#   core_fallback_action_name: "action_listen"
#   enable_fallback_prediction: True
assistant_id: 20231202-221250-mode-flour